# linux = RedHat Linux box, Intel icc, MPICH

SHELL = /bin/sh

# ---------------------------------------------------------------------
# compiler/linker settings
# specify flags and libraries needed for your compiler

CC =		g++
CCFLAGS =	-O2 -std=c++11 -I/usr/include/hdf5/serial/ -I/usr/include/eigen3/ -I/usr/include/mpi
DEPFLAGS =	-M
SHFLAGS =	-fPIC

LINK =		g++
LINKFLAGS =	-O2 -std=c++11
LIB =	  	-lstdc++
SIZE =		size

ARCHIVE =	ar
ARFLAGS =	-rc
SHLIBFLAGS =	-shared

# ---------------------------------------------------------------------
# SPPARKS-specific settings
# specify settings for SPPARKS features you will use

# SPPARKS ifdef options, see doc/Section_start.html

SPK_INC =	-DSPPARKS_GZIP -DSPPARKS_JPEG -DSPPARKS_HDF5 -DSPPARKS_EIGEN

# MPI library, can be src/STUBS dummy lib
# INC = path for mpi.h, MPI compiler settings
# PATH = path for MPI library
# LIB = name of MPI library

MPI_INC = -I../STUBS #      -DMPICH_SKIP_MPICXX
MPI_PATH = 
MPI_LIB = ../STUBS/libmpi.a #	-lmpich -lmpl -lpthread

# JPEG library, only needed if -DLAMMPS_JPEG listed with LMP_INC
# INC = path for jpeglib.h
# PATH = path for JPEG library
# LIB = name of JPEG library

JPG_INC =       
JPG_PATH = 	
JPG_LIB =	-ljpeg

# HDF5 library, only needed if -DSPPARKS_HDF5 is set in SPPARKS_INC

HDF_INC =   /usr/include/hdf5/serial/hdf5.h /usr/include/hdf5/serial/hdf5_hl.h /usr/include/hdf5/serial/H5Cpp.h
HDF_PATH =   /usr/lib/x86_64-linux-gnu/libhdf5_serial.so /usr/lib/x86_64-linux-gnu/libhdf5_serial_hl.so
HDF_LIB =   -lhdf5 -lhdf5_hl -lhdf5_cpp

# ---------------------------------------------------------------------
# build rules and dependencies
# no need to edit this section

EXTRA_INC = $(SPK_INC) $(MPI_INC) $(JPG_INC) $(HDF_INC)
EXTRA_PATH = $(MPI_PATH) $(JPG_PATH) $(HDF_PATH)
EXTRA_LIB = $(MPI_LIB) $(JPG_LIB) $(HDF_LIB)

# Link target

$(EXE):	$(OBJ)
	$(LINK) $(LINKFLAGS) $(EXTRA_PATH) $(OBJ) $(EXTRA_LIB) $(LIB) -o $(EXE)
	$(SIZE) $(EXE)

# Library targets

lib:	$(OBJ)
	$(ARCHIVE) $(ARFLAGS) $(EXE) $(OBJ)

shlib:	$(OBJ)
	$(CC) $(CCFLAGS) $(SHFLAGS) $(SHLIBFLAGS) $(EXTRA_PATH) -o $(EXE) \
        $(OBJ) $(EXTRA_LIB) $(LIB)

# Compilation rules

%.o:%.cpp
	$(CC) $(CCFLAGS) $(SHFLAGS) $(EXTRA_INC) -c $<

%.d:%.cpp
	$(CC) $(CCFLAGS) $(EXTRA_INC) $(DEPFLAGS) $< > $@

# Individual dependencies

DEPENDS = $(OBJ:.o=.d)
include $(DEPENDS)
